# SPDX-License-Identifier: GPL-2.0-only

LINUXINCLUDE += -I$(srctree)/

obj-$(CONFIG_OPLUS_FEATURE_AFS_CONFIG) += oplus_afs_config.o

# out-of-tree: source file is afs_config.c, module name is oplus_afs_config.
oplus_afs_config-y := afs_config.o
